// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import authActionCreatorsBase from "./actionCreators.base.generated";
import authActionCreatorsExtended from "./actionCreators.extended";

export const authActionCreators = { ...authActionCreatorsBase, ...authActionCreatorsExtended }

export default authActionCreators