// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import AuthenticatedUsers from "../../../interfaces/AuthenticatedUsers";
import AuthServices from "../../../interfaces/AuthServices";
import actions from "./../actions/action.base.generated";
        
export type AuthReducerActionsBase = { type: actions } & (
   | {
        type: actions.AUTH_SET_IS_INITIALIZED;
        next:  boolean;
    }   | {
        type: actions.AUTH_SET_IS_AUTHENTICATING;
        next:  boolean;
    }   | {
        type: actions.AUTH_SET_SERVICES;
        next:  AuthServices | undefined;
    }   | {
        type: actions.AUTH_SET_USERS;
        next:  AuthenticatedUsers | undefined;
    }
);

export const isAuthReducerActionsBase = (item: any): item is AuthReducerActionsBase => {
    if (!item) { return false; }
    if (typeof item === "object") {
        const { type } = item;

        return typeof type === "string" && actions.hasOwnProperty(type);
    }
    return false;
}

export default AuthReducerActionsBase