// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import AuthReducerActionsBase, { isAuthReducerActionsBase } from "./reducerActions.base.generated";
import AuthReducerActionsExtended, { isAuthReducerActionsExtended } from "./reducerActions.extended";

export type AuthReducerActions = AuthReducerActionsBase | AuthReducerActionsExtended;

export const isAuthReducerActions = (item: any): item is AuthReducerActions => {
    return isAuthReducerActionsBase(item) || isAuthReducerActionsExtended(item);
}

export default AuthReducerActions;
