// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import authReducerBase from "./reducer.base.generated";
import authReducerExtended from "./reducer.extended";
import { isAuthReducerActionsBase } from "./../reducerActions/reducerActions.base.generated";
import State from "./../state";
import getDefaultState from "./../defaultState.base.generated";
import AuthReducerActions from "./../reducerActions/reducerActions.main.generated";
        
export const authReducer = (state: State = getDefaultState(), action:  AuthReducerActions): State => {
    // Note: Generator may be extended to inversify this order => Just talk to me ;)
    // return authReducerExtended((isAuthReducerActionsBase(action) ? authReducerBase(state, action) : state), action);
    
    return (isAuthReducerActionsBase(action) ? authReducerBase(authReducerExtended(state, action), action) : authReducerExtended(state, action));
}

export default authReducer;
