// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import State from "./../state";
import getDefaultState from "./../defaultState.base.generated";
import ReducerAction from "./../reducerActions/reducerActions.base.generated";
import actions from "./../actions/action.base.generated";
            
const authReducerBase = (state: State = getDefaultState(), action: ReducerAction): State => {
    switch (action.type) {
       case actions.AUTH_SET_IS_INITIALIZED:
            return {
                ...state, 
                isInitialized: action.next,
            };
       case actions.AUTH_SET_IS_AUTHENTICATING:
            return {
                ...state, 
                isAuthenticating: action.next,
            };
       case actions.AUTH_SET_SERVICES:
            return {
                ...state, 
                services: action.next,
            };
       case actions.AUTH_SET_USERS:
            return {
                ...state, 
                users: action.next,
            };        
        default:
            return state; 
    }
}


export default authReducerBase