// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import State from "./state";
        
export const getAuthDefaultState = (): State => ({
    isInitialized: false,
    isAuthenticating: false,
    services: undefined,
    users: undefined,
  
});

export default getAuthDefaultState