// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import { AuthReducerActions as RAs } from "./reducerActions/reducerActions.main.generated";
export { authReducer } from "./reducer/reducer.main.generated";
export { AUTH_ACTIONS } from "./actions/action.main.generated";
export { authActionCreators } from "./actionCreators/actionCreators.main.generated";
export * from "./ReducerContext.main.generated";

export type AuthReducerActions = RAs 
