// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

import AUTH_ACTIONS_BASE from "./action.base.generated";
import AUTH_ACTIONS_EXTENDED from "./action.extended";
        
export const AUTH_ACTIONS = { ...AUTH_ACTIONS_BASE, ...AUTH_ACTIONS_EXTENDED };

export default AUTH_ACTIONS