// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.
// DO NOT Change anything inside this file. Every time the generator is used, it will be overwritten.

export enum AUTH_ACTIONS_BASE {
    AUTH_SET_IS_INITIALIZED = "AUTH_SET_IS_INITIALIZED",
    AUTH_SET_IS_AUTHENTICATING = "AUTH_SET_IS_AUTHENTICATING",
    AUTH_SET_SERVICES = "AUTH_SET_SERVICES",
    AUTH_SET_USERS = "AUTH_SET_USERS",
}

export default AUTH_ACTIONS_BASE;
