// This file has been generated by reducer-gen (@Stefan Pauka) written in 2020.

export enum AUTH_ACTIONS_EXTENDED {
    // e.g. SET_IS_LOGGED_IN_EXT = "SET_IS_LOGGED_IN_EXT",
    SET_AUTH_PROVIDER_SERVICE = "SET_AUTH_PROVIDER_SERVICE",
    SET_AUTH_USER = "SET_AUTH_USER",
}

export default AUTH_ACTIONS_EXTENDED;
